name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "44a11e7d2e40463cbb369725073f584b" },
  { binding = "SHARE", id = "0481c4af553a412d96f5ccbe5ad752ca" }
]